export const browserCoreExamples = [
  "gimli browser status",
  "gimli browser start",
  "gimli browser stop",
  "gimli browser tabs",
  "gimli browser open https://example.com",
  "gimli browser focus abcd1234",
  "gimli browser close abcd1234",
  "gimli browser screenshot",
  "gimli browser screenshot --full-page",
  "gimli browser screenshot --ref 12",
  "gimli browser snapshot",
  "gimli browser snapshot --format aria --limit 200",
  "gimli browser snapshot --efficient",
  "gimli browser snapshot --labels",
];

export const browserActionExamples = [
  "gimli browser navigate https://example.com",
  "gimli browser resize 1280 720",
  "gimli browser click 12 --double",
  'gimli browser type 23 "hello" --submit',
  "gimli browser press Enter",
  "gimli browser hover 44",
  "gimli browser drag 10 11",
  "gimli browser select 9 OptionA OptionB",
  "gimli browser upload /tmp/file.pdf",
  'gimli browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "gimli browser dialog --accept",
  'gimli browser wait --text "Done"',
  "gimli browser evaluate --fn '(el) => el.textContent' --ref 7",
  "gimli browser console --level error",
  "gimli browser pdf",
];
